### ISSUE TITLE
MRFs for text segment alignments 

### ISSUE THREAD

**Issue by pradeepkaruturi** [karpathy/neuraltalk#12]
Hi Andrej,
 Thank you very much for open sourcing the code! 
 You paper talks about MRFs for decoding text segment alignments to images, but I couldn't find any code related to that. Am I missing something?

Thanks
Pradeep.

**Comment by sxjzwq** [comment]
Me too. It seems that there is no code for that part.
@karpathy , do you have any plan to publish the code of that part (text segment alignment using MRF).

Thanks.
Qi

**Comment by karpathy** [comment]
Hi, there are two models in my paper: an alignment/retrieval model and a generation model. I released the generation model. The retrieval model does ranking (image -> sentence or vice versa), and includes computing the alignments, etc. This part was not released.
