### ISSUE TITLE
How to generate json for new data?

### ISSUE THREAD

**Issue by VanessaD** [karpathy/neuraltalk#13]
Hi Andrej, 
I was interested in using your algorithm for some new data. Basically, each images is associated with one sentence. Is there a convenient way to generate the json file as in your example (Flickr8k, etc). What is the structure of the json, and is there anyway to not using json format? 

Thanks!
Wei

**Comment by karpathy** [comment]
Hi, there isn't any explicit code for this. Look at the json's manually and inspect the DataProvider class. I think it's relatively simple so I didn't add any explicit utilities.
