### ISSUE TITLE
init_model_from argument has no effect on where driver starts

### ISSUE THREAD

**Issue by EricZeiberg** [karpathy/neuraltalk#28]
It seems like, even when a checkpoint file is passed into `--init_model_from` argument, it starts from epoch 0.00 and acts like the initial model was never even passed in.

**Comment by karpathy** [comment]
it's init_from, not resume_from. it loads in the weights but it doesnt actually start the optimization from scratch. i decided that it would be slightly tricky and didn't have time to do it.

**Comment by EricZeiberg** [comment]
Oh alright
