### ISSUE TITLE
Have you implemented Visual-Semantic Alignments ?

### ISSUE THREAD

**Issue by qmiwang** [karpathy/neuraltalk#40]
Thanks for your kindness to release these codes!
 It helps me a lot!
I am interested in your cvpr paper : Deep Visual-Semantic Alignments for Generating Image Descriptions.  But I did not found anything about Visual-Semantic Alignments in this released code, have I missed something ? thanks !

**Comment by healthyjk** [comment]
I think you can download the code of his paper in nips 2014 from here  http://cs.stanford.edu/people/karpathy/. I think it's a basic prototype of Visual-Semantic Alignment.

**Comment by qmiwang** [comment]
@healthyjk Thank you !

**Comment by karpathy** [comment]
I did not release the ranking part, only the generation part. The NIPS code gives the gist though.
